/* Base de datos POKEMON */

# Creamos la base de datos

DROP DATABASE IF EXISTS INFORMACION;
CREATE DATABASE INFORMACION;
DROP USER IF EXISTS InformacionAdmin;
CREATE USER InformacionAdmin IDENTIFIED BY 'InformacionPass';
GRANT ALL PRIVILEGES ON INFORMACION.* TO InformacionAdmin WITH GRANT OPTION;
USE INFORMACION;

# Creamos las tablas
CREATE TABLE CONTACTES(
	TELEFON INT(9) PRIMARY KEY,
    NOM VARCHAR(40),
    DIRECTORA VARCHAR(40),
    SERVEIes VARCHAR(100),
    SERVEIen VARCHAR(100),
    SERVEIca VARCHAR(100),
    ADRECA VARCHAR(100),
    LONGITUT DOUBLE(6,4),
    LATITUT DOUBLE(6,4)
);

USE INFORMACION;
INSERT INTO CONTACTES VALUES(936970513,"Hospital", "Belen", "Ayuda","Help","Ajuda","Calle sdalksdja",21.2323,32.3213);
